### ISSUE TITLE
turn on device on boot

### ISSUE THREAD

**Issue by h4de5** [h4de5/esphome-configs#1]
```
esphome:
 name: $devicename
 platform: ESP8266
 board: esp8285
 on_boot:
   then:
     - switch.turn_on: relay
```
